### ISSUE TITLE
Prerendered site will re-fetch md

### ISSUE THREAD

**Issue by jthegedus** [egoist/docute#207]
Using [`presite`](https://github.com/egoist/presite) to create static html of a Docute site is great, except I have found that each route has

```html
    <script>
      new Docute({
        target: "#docute",
	    ...
      });
    </script>
```

which means that when the HTML finishes loading, Docute will re-fetch the `.md` for the particular route and re-mount it to the `target: "#docute"` div.

This creates two issues:

1. there is a flash of loaded content, then Docute loading visual, then the newly computed content.
2. the content is fetched from the network again.

I'm not sure where a flag would go to stop this from occurring, but an option like so would be nice:

```html
    <script>
      new Docute({
        target: "#docute",
		 fetchContent: false,
	    ...
      });
    </script>
```

I've tried removing the `new Docute` script from the `presite` output HTML, but this causes the issues with dynamic features like toggling light/dark theme.

Related: #34, #174

**Comment by egoist** [comment]
https://github.com/leptosia/docute/commit/1b02d0f063db00bc357542b5c0bb7d0dd70cfc5c

this commit adds pre-render support, kinda like the way Vue SSR works:

- during pre-render (when user agent matches `/(Prerender|jsdom|PhantomJS)/i`, it will inject initial state as `<script>window.__DOCUTE_INITIAL_STATE__ = {...state}</script>` to the document.
- in actual browser it will use `window.__DOCUTE_INITIAL_STATE__` instead of fetching file if possible.

you need to re-install `presite` since I updated the [user agent](https://github.com/egoist/taki/commit/95677adffdd481488b13525fae01feeb33371888) there.

---

the generated html is kinda large tho, something needs to be done to reduce the size.

**Comment by jthegedus** [comment]
@egoist cheers, I'll give it a go.

**Comment by jthegedus** [comment]
Thanks for your work on this. It fixes the re-fetching so I will close this issue.

But I do wish to flag that I still see a flash of the content-loading animation sometimes when changing routes. I'm unsure what the cause is other than the router always displaying this while checking the cache for data.
